### ISSUE TITLE
[GUI] change the + to a checkmark when chapter is added to library

### ISSUE THREAD

**Issue by BanditKingJing** [Doomsdayrs/shosetsu#65] opened 2020-01-04 05:34 UTC
![Screenshot_20200104-001923_Shosetsu](https://user-images.githubusercontent.com/53633953/71760329-f9871c00-2e89-11ea-94ca-759b16c898ad.jpg)
Title

**Comment by hXtreme** [comment] 2020-01-04 05:57
Partial duplicate of #9

**Closed** 2020-01-04 06:03 UTC
Labels: bug
